[package]
name = "rust-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
futures-util = "0.3.33"
http = "1.5.0"
reqwest-sse = "0.2.0"
sysinfo = "0.39.6"
tokio = {version = "1.53.1", features = ["full"]}
tokio-stream = "0.1.19"
tower-http = {version = "0.7.0", features = ["cors"]}

[target.'cfg(target_os = "linux")']
runner = "sh -c 'sudo setcap cap_net_bind_service=+ep \"$0\" && \"$0\"'"
